script = ['import nd2' newline ...
'import numpy as np' newline ...
'import os' newline ...
'os.makedirs(''./sequential'', exist_ok=True)' newline ...
'f = nd2.ND2File(''/scratch/bazzi/20260612_ANS9_mNG_GAM488_R2_denoised/20260612_ANS9_mNG_GAM488_R2_crop_1.nd2'')' newline ...
'arr = f.asarray()' newline ...
'num_fov = arr.shape[0]' newline ...
'HYB = 0' newline ...
'CHANNEL_NAMES = [''SD561'', ''SD488'', ''SD405'']' newline ...
'for fov in range(num_fov):' newline ...
'    for ch in range(3):' newline ...
'        stack = arr[fov, :, ch, :, :]' newline ...
'        np.save(f''./sequential/{CHANNEL_NAMES[ch]}_{HYB}_{fov+1}.npy'', stack)' newline ...
'        print(f''Saved {CHANNEL_NAMES[ch]} FOV {fov+1}'')' newline ...
'f.close()' newline ...
'print(''Done'')' newline];
fid = fopen('convert_nd2_v2.py', 'w');
fprintf(fid, '%s', script);
fclose(fid);
system('python convert_nd2_v2.py');

%% 
